server.port=8761
spring.application.name=eureka-server

# Como es el propio servidor, no necesita registrarse a si mismo ni buscar otros
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false